apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-1-deploy

spec:
  selector:
    matchLabels:
      app: ecommerce-1-deploy

  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-1-deploy
    spec:
      containers:
        - name: ecommerce-1-deploy
          image: daramallapavan/ecom-springboot
   #       imagePullPolicy: ifNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-1-service
spec:
  selector:
    app: ecommerce-1-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort